#!/bin/bash
echo -e "\033[1;33mBadVpn\033[1;30m
1) Activar juegos online, llamadas whatsapp
2) Parar servicio de badvpn"
read -p "opcion: " option
if [ $option -eq 1 ]; then
badvpn start
exit 0
fi

if [ $option -eq 2 ]; then
badvpn stop
exit
fi
