#!/bin/bash
if [ $(id -u) -eq 0 ]
then
clear
else
echo -e "Ejecute el script como usuario \033[1;32mroot\033[0m"
exit
fi
if [ -d /etc/VpsPackdir ]
then
true
else
mkdir /etc/VpsPackdir
fi
if [ -d /etc/VpsPackdir/senha ]
then
true
else
mkdir /etc/VpsPackdir/senha
fi
if [ -d /etc/VpsPackdir/limite ]
then
true
else
mkdir /etc/VpsPackdir/limite
fi

function configurarsquid(){
clear
cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/	//' > /etc/so 
if [ -f /etc/lsb-release ]
then
sistema=$(cat /etc/lsb-release |grep "DISTRIB_DESCRIPTION" | awk -F = '{print $2}' |sed 's/"//g')
else
sistema=Null
fi
echo -e "\033[1;36mPara que la instalacion sea correcta se necesita una ip.
Digite su ip !\033[0m"
read -p ": " ip
clear
echo -e "\033[1;36m-----> \033[01;37mVPS Manager - V3\033[0m"
echo -e "\033[1;36m-----> \033[01;37mSistema:\033[1;36m $sistema"
echo -e "\033[1;36m-----> \033[01;37mSu IP agregada:\033[1;36m $ip"
echo -e "\033[1;36m-----> \033[1;37mSQUID:\033[1;36m 80, 8080, 8799, 3128\033[0m"
echo -e "\033[1;36m-----> \033[1;37mPuertos SSH: \033[1;36m443, 22\033[0m"
echo -e "\033[1;36m-----> \033[1;37mDropbear Puertos: \033[1;36m444\033[0m"
echo -e "\033[1;36m-----> \033[1;37mIPS/Hosts SSH: \033[1;36m$ip, localhost, 127.0.0.1\033[0m"
echo -e "\033[1;36m-----> \033[1;37mHerramienta para agregar Hosts:\033[1;36m addhost\033[0m"

function sshd_config(){ 
echo 'Port 443
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
' >> /etc/ssh/sshd_config
}

function addihost(){ echo '#!/bin/bash
echo -e "\033[1;36mHosts atualmente permitidos\n\n\033[1;32m$(cat /etc/payloads)\n\033[0m"
echo "¿Que host desea agregar?"
read -p ": " host
echo "$host" >> /etc/payloads
squid -k reconfigure > /dev/null 2> /dev/null
squid3 -k reconfigure > /dev/null 2> /dev/null
echo "$host Agregado" ' > /bin/addhost
chmod a+x /bin/addhost
}
function removerhostf(){ echo '#!/bin/bash
echo -e "\033[1;36mHosts atualmente permitidos\n\n\033[1;32m$(cat /etc/payloads)\n\033[0m"
echo -ne "\033[1;37m¿Cual host desea eliminar?: \033[0m"
read host
hosts = $(cat /etc/payloads |grep -v $host)
echo "$hosts" > /etc/payloads
squid -k reconfigure >/dev/null 2>/dev/null
squid3 -k reconfigure >/dev/null 2>/dev/null
echo -e "\n\033[1;32mHost Eliminado\033[0m"
' > /bin/removerhost
}
function payloads(){ echo ".claro.com.br
.claro.com.sv
.vivo.com.br
.ddivulga.com" > /etc/payloads
}

if cat /etc/so |grep -i ubuntu |grep 16 1> /dev/null 2> /dev/null ; then
echo -e "\033[1;37mConfigurando, Espere...\033[0m"
apt-get update 1> /dev/null 2> /dev/null
apt-get install -y squid3 1> /dev/null 2> /dev/null

service apache2 stop 1> /dev/null 2> /dev/null
chattr -i /etc/ssh/sshd_config > /dev/null 2> /dev/null
sshd_config
service ssh restart 1> /dev/null 2> /dev/null

echo "http_port 80
http_port 8080
http_port 8799
http_port 3128
visible_hostname VpsPack
acl ip dstdomain $ip
http_access allow ip" > /etc/squid/squid.conf
echo 'acl accept dstdomain -i "/etc/payloads"
http_access allow accept
acl local dstdomain localhost
http_access allow local
acl iplocal dstdomain 127.0.0.1
http_access allow iplocal
http_access deny all' >> /etc/squid/squid.conf

addihost
removerhostf
payloads
service squid restart 1> /dev/null 2> /dev/null
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=444/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 80"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service ssh restart
service dropbear restart
echo -e "\033[1;37mPara agregar nuevos hosts escriba: \033[1;32maddhost
\033[1;37mPara quitar un host escriba: \033[1;32mremoverhost\033[1;37m
Los hosts se encuentran en el archivo: /etc/payloads\033[0m"
echo -e "\033[01;36mFinalizado !! \033[0m"
echo -e "\033[01;36mPuertos Agregados: \033[0m"
echo -e "\033[01;36mOpenSSH: 22/443 \033[0m"
echo -e "\033[01;36mSquid: 80/8080/8799/3128 \033[0m"
echo -e "\033[01;36mDropbear: 444 \033[0m"
exit 0
fi

if cat /etc/so |grep -i ubuntu 1> /dev/null 2> /dev/null ; then
echo -e "\033[1;37mConfigurando, Espere...\033[0m"
apt-get update 1> /dev/null 2> /dev/null
apt-get install -y squid3 1> /dev/null 2> /dev/null

service apache2 stop 1> /dev/null 2> /dev/null
chattr -i /etc/ssh/sshd_config > /dev/null 2> /dev/null
sshd_config
service ssh restart 1> /dev/null 2> /dev/null

echo "http_port 80
http_port 8080
http_port 8799
http_port 3128
visible_hostname VpsPack
acl ip dstdomain $ip
http_access allow ip" > /etc/squid3/squid.conf
echo 'acl accept dstdomain -i "/etc/payloads"
http_access allow accept
acl local dstdomain localhost
http_access allow local
acl iplocal dstdomain 127.0.0.1
http_access allow iplocal
http_access deny all' >> /etc/squid3/squid.conf
payloads
service squid3 restart 1> /dev/null 2> /dev/null
addihost
removerhostf
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=444/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 80"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service ssh restart
service dropbear restart
echo -e "\033[1;37mPara agregar nuevos hosts escriba: \033[1;32maddhost
\033[1;37mPara quitar un host escriba: \033[1;32mremoverhost\033[1;37m
Los hosts se encuentran en el archivo: /etc/payloads\033[0m"
echo -e "\033[01;36mFinalizado !! \033[0m"
echo -e "\033[01;36mPuertos Agregados: \033[0m"
echo -e "\033[01;36mOpenSSH: 22/443 \033[0m"
echo -e "\033[01;36mSquid: 80/8080/8799/3128 \033[0m"
echo -e "\033[01;36mDropbear: 444 \033[0m"
exit 0
fi

if cat /etc/so |grep -i centos 1> /dev/null 2> /dev/null ; then
echo -e "\033[01;37mConfigurando, Espere...\033[0m"
yum -y update 1> /dev/null 2> /dev/null
yum install -y squid 1> /dev/null 2> /dev/null

service httpd stop 1> /dev/null 2> /dev/null
chattr -i /etc/ssh/sshd_config > /dev/null 2> /dev/null
sshd_config
service sshd restart 1> /dev/null 2> /dev/null

echo "http_port 80
http_port 8080
http_port 8799
http_port 3128
visible_hostname VpsPack
acl ip dstdomain $ip
http_access allow ip" > /etc/squid/squid.conf
echo 'acl accept dstdomain -i "/etc/payloads"
http_access allow accept
acl local dstdomain localhost
http_access allow local
acl iplocal dstdomain 127.0.0.1
http_access allow iplocal
http_access deny all' >> /etc/squid/squid.conf
payloads
service squid restart 1> /dev/null 2> /dev/null
addihost
removerhostf
echo -e "\033[1;37mPara agregar nuevos hosts escriba: \033[1;32maddhost
\033[1;37mPara quitar un host escriba: \033[1;32mremoverhost\033[1;37m
Los hosts se encuentran en el archivo: /etc/payloads\033[0m"
echo -e "\033[01;36mFinalizado !! \033[0m"
echo -e "\033[01;36mPuertos Agregados: \033[0m"
echo -e "\033[01;36mOpenSSH: 22/443 \033[0m"
echo -e "\033[01;36mSquid: 80/8080/8799/3128 \033[0m"
echo -e "\033[01;36mDropbear: 444 \033[0m"
exit
fi

if cat /etc/so |grep -i debian 1> /dev/null 2> /dev/null ; then
echo -e "\033[01;37mConfigurando, Espere...\033[0m"
apt-get update 1> /dev/null 2> /dev/null
apt-get install -y squid3 1> /dev/null 2> /dev/null
service apache2 stop 1> /dev/null 2> /dev/null
chattr -i /etc/ssh/sshd_config > /dev/null 2> /dev/null
sshd_config

service ssh restart 1> /dev/null 2> /dev/null

echo "http_port 80
http_port 8080
http_port 8799
http_port 3128
visible_hostname VpsPack
acl ip dstdomain $ip
http_access allow ip" > /etc/squid3/squid.conf
echo 'acl accept dstdomain -i "/etc/payloads"
http_access allow accept
acl local dstdomain localhost
http_access allow local
acl iplocal dstdomain 127.0.0.1
http_access allow iplocal
http_access deny all' >> /etc/squid3/squid.conf
payloads
service squid3 restart 1> /dev/null 2> /dev/null
addihost
removerhostf
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=443/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 443 -p 80"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service ssh restart
service dropbear restart
echo -e "\033[1;37mPara agregar nuevos hosts escriba: \033[1;32maddhost
\033[1;37mPara quitar un host escriba: \033[1;32mremoverhost\033[1;37m
Los hosts se encuentran en el archivo: /etc/payloads\033[0m"
echo -e "\033[01;36mFinalizado !! \033[0m"
echo -e "\033[01;36mFinalizado, cree un usuario de prueba !! \033[0m"
echo -e "\033[01;36mPuertos Agregados: \033[0m"
echo -e "\033[01;36mOpenSSH: 22/443 \033[0m"
echo -e "\033[01;36mSquid: 80/8080/8799/3128 \033[0m"
echo -e "\033[01;36mDropbear: 444 \033[0m"
exit 0
fi
if cat /etc/issue |grep -i kernel 1> /dev/null 2> /dev/null ; then
echo -e "\033[01;36mConfigurando, Espere...\033[0m"
yum -y update 1> /dev/null 2> /dev/null
yum install -y squid 1> /dev/null 2> /dev/null

service httpd stop 1> /dev/null 2> /dev/null
chattr -i /etc/ssh/sshd_config > /dev/null 2> /dev/null
sshd_config
service sshd restart 1> /dev/null 2> /dev/null

echo "http_port 80
http_port 8080
http_port 8799
http_port 3128
visible_hostname VpsPack
acl ip dstdomain $ip
http_access allow ip" > /etc/squid/squid.conf
echo 'acl accept dstdomain -i "/etc/payloads"
http_access allow accept
acl local dstdomain localhost
http_access allow local
acl iplocal dstdomain 127.0.0.1
http_access allow iplocal
http_access deny all' >> /etc/squid/squid.conf
payloads
service squid restart 1> /dev/null 2> /dev/null
addihost
removerhostf
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=444/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 80"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service ssh restart
service dropbear restart
sudo ssserver -c /etc/shadowsocks.json -d start
echo -e "\033[1;37mPara agregar nuevos hosts escriba: \033[1;32maddhost
\033[1;37mPara quitar un host escriba: \033[1;32mremoverhost\033[1;37m
Los hosts se encuentran en el archivo: /etc/payloads\033[0m"
echo -e "\033[01;36mFinalizado !! \033[0m"
echo -e "\033[01;36mPuertos Agregados: \033[0m"
echo -e "\033[01;36mOpenSSH: 22/443 \033[0m"
echo -e "\033[01;36mSquid: 80/8080/8799/3128 \033[0m"
echo -e "\033[01;36mDropbear: 444 \033[0m"
exit
fi
echo -e "\033[01;36mConfigurando, Espere...\033[0m"
yum -y update 1> /dev/null 2> /dev/null
yum install -y squid 1> /dev/null 2> /dev/null
apt-get update > /dev/null 2> /dev/null
apt-get install -y squid3 > /dev/null 2>/dev/null
service httpd stop 1> /dev/null 2> /dev/null
service apache2 stop >/dev/null 2> /dev/null
chattr -i /etc/ssh/sshd_config > /dev/null 2> /dev/null
sshd_config
service sshd restart 1> /dev/null 2> /dev/null
service ssh restart > /dev/null 2> /dev/null
echo "http_port 80
http_port 8080
http_port 8799
http_port 3128
visible_hostname VpsPack
acl ip dstdomain $ip
http_access allow ip" > /etc/squid*/squid.conf
echo 'acl accept dstdomain -i "/etc/payloads"
http_access allow accept
acl local dstdomain localhost
http_access allow local
acl iplocal dstdomain 127.0.0.1
http_access allow iplocal
http_access deny all' >> /etc/squid*/squid.conf
payloads
service squid restart 1> /dev/null 2> /dev/null
service squid3 restart > /dev/null 2> /dev/null
addihost
removerhostf
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=444/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 80"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service ssh restart
service dropbear restart
echo -e "\033[1;37mPara agregar nuevos hosts escriba: \033[1;32maddhost
\033[1;37mPara quitar un host escriba: \033[1;32mremoverhost\033[1;37m
Los hosts se encuentran en el archivo: /etc/payloads\033[0m"
echo -e "\033[01;36mFinalizado !! \033[0m"
echo -e "\033[01;36mPuertos Agregados: \033[0m"
echo -e "\033[01;36mOpenSSH: 22/443 \033[0m"
echo -e "\033[01;36mSquid: 80/8080/8799/3128 \033[0m"
echo -e "\033[01;36mDropbear: 444 \033[0m"
}
function sistemadetalhes(){
if [ -f /proc/cpuinfo ]
then
echo -e "\n\033[1;30mProcessador\033[0m"
modelo=$(cat /proc/cpuinfo |grep "model name" |uniq |awk -F : {'print $2'})
cpucores=$(cat /proc/cpuinfo |grep "cpu cores" |uniq |awk -F : {'print $2'})
cache=$(cat /proc/cpuinfo |grep "cache size" |uniq |awk -F : {'print $2'})
echo -e "\033[1;32mModelo:\033[0m$modelo"
echo -e "\033[1;32mNucleos:\033[0m$cpucores"
echo -e "\033[1;32mMemoria Cache:\033[0m$cache"
echo -e "\033[1;32mArquitetura: \033[0m$(uname -p)"
else
echo -e "\033[1;30mProcessador\033[0m"
echo "No fue posible encontrar /proc/cpuinfo"
fi
if [ -f /etc/lsb-release ]
then
echo -e "\n\033[1;30mSistema Operativo\033[0m"
name=$(cat /etc/lsb-release |grep DESCRIPTION |awk -F = {'print $2'})
codename=$(cat /etc/lsb-release |grep CODENAME |awk -F = {'print $2'})
echo -e "\033[1;32mNome: \033[0m$name"
echo -e "\033[1;32mCodeName: \033[0m$codename"
echo -e "\033[1;32mKernel: \033[0m$(uname -s)"
echo -e "\033[1;32mKernel Release: \033[0m$(uname -r)"
if [ -f /etc/os-release ]
then
devlike=$(cat /etc/os-release |grep LIKE |awk -F = {'print $2'})
echo -e "\033[1;32mDerivado del sistema OS: \033[0m$devlike"
fi
else
echo -e "\n\033[1;30mSistema Operativo\033[0m"
echo "No fue posible encontrar /etc/lsb-release"
fi
if free 1>/dev/null 2>/dev/null
then
echo -e "\n\033[1;30mMemoria RAM\033[0m"
echo -e "\033[1;32mTotal: \033[0m$(free -m |grep -i mem |awk {'print $2'}) MB | $(( $(free -m |grep -i mem |awk {'print $2'}) / 1024 )) GB"
echo -e "\033[1;32mEn Uso: \033[0m$(free -m |grep -i mem |awk {'print $3'}) MB | $(( $(free -m |grep -i mem |awk {'print $3'}) / 1024 )) GB"
echo -e "\033[1;32mLibre: \033[0m$(free -m |grep -i mem |awk {'print $4'}) MB | $(( $(free -m |grep -i mem |awk {'print $4'}) / 1024 )) GB"
echo -e "\n\033[1;30mSwap\033[0m"
echo -e "\033[1;32mTotal: \033[0m$(free -m |grep -i swap |awk {'print $2'}) MB | $(( $(free -m |grep -i swap |awk {'print $2'}) / 1024 )) GB"
echo -e "\033[1;32mEn Uso: \033[0m$(free -m |grep -i swap |awk {'print $3'}) MB | $(( $(free -m |grep -i swap |awk {'print $3'}) / 1024 )) GB"
echo -e "\033[1;32mLibre: \033[0m$(free -m |grep -i swap |awk {'print $4'}) MB | $(( $(free -m |grep -i swap |awk {'print $4'}) / 1024 )) GB"
else
echo -e "\n\033[1;30mMemoria RAM\033[0m"
echo "No fue posible obtener informacion sobre la memoria RAM"
fi
}
function monitorar(){
clear
echo -e "\033[1;37m -------------------------------------------------------\033[0m"
echo -e " \033[47;30m   Usuarios           :        Conexiones Simultaneas.   \033[0m"
echo -e "\033[1;37m -------------------------------------------------------\033[0m"
for usur in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9] |sort`; do
if [ -f /etc/VpsPackdir/limite/$usur ]; then
limite=$(cat -n /etc/VpsPackdir/limite/$usur |awk '$1 = 1 {print $2}')
else
limite=null
fi
usurnum="$(ps -u $usur |grep sshd |wc -l)\033[1;30m/\033[1;33m$limite"
echo -e "\033[1;33m    $(printf '%-41s%s' $usur $usurnum) \033[0m"
echo -e "\033[1;37m -------------------------------------------------------\033[0m"
done
}
function removerexpirados(){
clear
echo -e "         \033[1;33mRemover Usuarios Expirados\033[0m"
datahoje=$(date +%s)
for user in $(cat /etc/passwd |grep -v "nobody" |awk -F : '$3 > 900 {print $1}')
do
dataexp=$(chage -l $user |grep "Account expires" |awk -F : '{print $2}')
if [[ $dataexp == ' never' ]]; then
id > /dev/null 2>/dev/null
else
dataexpn=$(date -d"$dataexp" '+%d/%m/%Y')
dataexpnum=$(date '+%s' -d"$dataexp")
fi
if [[ $dataexpnum < $datahoje ]]; then
printf "\033[1;36m"
printf '%-41s' $user
printf "\033[0m"
echo "Usuario expirado eliminado"
kill $(ps -u $user |awk '{print $1}') >/dev/null 2>/dev/null ; userdel $user
else
printf "\033[1;32m"
printf '%-41s' $user
printf "\033[0m"
echo $dataexpn
fi
done
}
function criarusuarioteste(){
mkdir /etc/usuariosteste 1>/dev/null 2>/dev/null
echo -e "   Usuarios de prueba"
for testus in $(ls /etc/usuariosteste |sort |sed 's/.sh//g')
do
echo "$testus"
done
printf "\n"
printf "Nombre del usuario: "; read nome
printf "Contraseña del usuario: "; read pass
echo -e "\nUsa s = segundos, m = minutos, h = horas e d = dias Ejemplo: 14s ."
printf "Cuanto tiempo la cuenta $nome debe durar: ";read tempoin
tempo=$(echo "$tempoin" |sed 's/ //g')
useradd -M -s /bin/false $nome
(echo $pass;echo $pass) |passwd $nome 1>/dev/null 2>/dev/null
echo "#!/bin/bash
sleep $tempo
kill"' $(ps -u '"$nome |awk '{print"' $1'"}') 1>/dev/null 2>/dev/null
userdel --force $nome
rm -rf /etc/usuariosteste/$nome.sh
exit" > /etc/usuariosteste/$nome.sh
echo -e "Usuario: $nome
Senha: $pass
Validade: $tempo\n
Despues de expirar, los usuarios seran desconectados."
bash /etc/usuariosteste/$nome.sh &
exit
}
function new_banner(){
wget https://raw.githubusercontent.com/diesel09/ban/master/banner.sh && bash banner.sh && rm -r banner.sh
}
function badvpn_install(){
wget https://raw.githubusercontent.com/diesel09/mx2/master/badvpn && bash badvpn
}
function shadowsocks_install(){
wget -qO- https://github.com/diesel09/conf/blob/master/setup-shadowsocks-on-debian.sh | bash
}
function removerlimite(){
echo -ne "\033[1;32mNombre del usuario a modificar: \033[0m"
read user
cronsemuser=$(cat /etc/crontab |grep -v "#$user#")
echo "$cronsemuser" > /etc/crontab
rm -rf /etc/VpsPackdir/limite/$user 2>/dev/null
rm -rf /etc/VpsPackdir/limite/$user.sh 2>/dev/null
pids=$(ps x |grep "#$user#" |awk {'print $1'})
kill $pids 2>/dev/null
kill "$pids" 2>/dev/null
kill -9 `ps x |grep "#$user#" |awk {'print $1'}` 2>/dev/null
kill `ps x |grep "#$user#" |awk {'print $1'}` 2>/dev/null
echo -e "\033[1;37mUsuario: $user, Limite removido\033[0m"
}
function backup_de_usuarios(){
clear
echo -e "\033[1;37mHaciendo Backup de Usuarios...\033[0m"
for user in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]`
do
if [ -e /etc/VpsPackdir/senha/$user ]
then
pass=$(cat /etc/VpsPackdir/senha/$user)
else
echo -e "\033[1;36mNo fue posible obtener la contraseña del usuario\033[1;37m ($user)"
read -p "Introduzca la contraseña manualmente o pulse ENTER: " pass
fi

if [ -e /etc/VpsPackdir/limite/$user ]
then
limite=$(cat /etc/VpsPackdir/limite/$user)
echo "$user:$pass:$limite" >> /etc/VpsPackdir/backup
echo -e "\033[1;37mUser $user Backup [\033[1;36mOK\033[1;37m]\033[0m"
else
echo "$user:$pass" >> /etc/VpsPackdir/backup
echo -e "\033[1;37mUser $user Backup [\033[1;36mOK\033[1;37m]\033[0m"
fi
done
echo " "
echo -e "\033[1;36mBackup Completado !!!\033[0m"
echo " "
echo -e "\033[1;37mLa informacion de los usuarios se encuentra en el archivo \033[1;36m /etc/VpsPackdir/backup \033[1;37m
Guardelo para una futura restauracion\033[0m"
}
function mudarnome(){
printf "Usuario al cual desea cambiarle el nombre: "; read user
if cat /etc/passwd |grep $user: >/dev/null 2>/dev/null
then
printf ""
else
echo "Usuario no existe"
exit
fi
printf "Nuevo nombre para el usuario $user: "; read nome
usermod -l $nome $user 1>/dev/null 2>/dev/null
echo -e "\nUsuario: $user, Nuevo nombre: $nome."
exit
}
function firewallblock(){
read -p "Escriba la direccion ip de su Vps: " ip
echo Configurando...
sleep 1
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp -d $ip --dport 443 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p tcp -d $ip --dport 80 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p tcp --dport 53 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p tcp --dport 67 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p udp --dport 67 -m state --state NEW -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
iptables -A INPUT -p tcp --dport 8799 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8080 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 3128 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 8799 -j ACCEPT
iptables -A FORWARD -p tcp --dport 8080 -j ACCEPT
iptables -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -p tcp --dport 3128 -j ACCEPT
iptables -A FORWARD -p tcp --dport 8799 -j ACCEPT
iptables -A INPUT -p icmp --icmp-type echo-request -j DROP
iptables -A INPUT -p tcp --dport 10000 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 10000 -j ACCEPT
echo -e "\033[1;37mFirewall modificado
Puertos 443 22 8799 8080 80 3128
Bloqueado ICMP
Bloqueado Torrent\033[0m"
}
function dropbear(){
cd ~/
./dropbear
}
function resetfirewall(){
iptables -F
iptables -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t nat -F
iptables -t nat -X
iptables -t filter -F
iptables -t filter -X
echo "Reglas restablecidas"
}
function detalhes_usuarios(){
clear

echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m Usuarios          Contraseña           Fecha Exp.         Logins Sim. \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
for users in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |sort |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do

if cat /etc/VpsPackdir/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/VpsPackdir/limite/$users)
else
limitecs="null"
fi

if  senha=$(cat /etc/VpsPackdir/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/VpsPackdir/senha/$users)
else
senha="null"
fi

data=$(chage -l $users |grep -i co |awk -F : '{print $2}')
if [ $data = never ] 2> /dev/null
then
date="Nunca"
fi
detalhesdata=$(printf '%-18s' "$data")
detalheslimit=$(printf '%-10s' "$limitecs")
detalhes=$(printf ' %-21s' "$users")
detalhespass=$(printf '%-18s' "$senha")
echo -e "\033[1;33m$detalhes $detalhespass $detalhesdata $detalheslimit\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
done
}
function restaurar_usuarios(){
echo -n "Escriba el directorio del archivo Backup: "
read arq
echo -e "\033[1;37mRestaurando Usuarios...\033[0m"

for user in `cat $arq`
do
usuario=$(echo "$user" |awk -F : '{print $1}')
senha=$(echo "$user" |awk -F : '{print $2}')
if cat /etc/passwd |grep $usuario: 1> /dev/null 2>/dev/null
then
echo " " > /dev/null
else
echo "$user" |cut -d: -f3 1> /dev/null 2>/dev/null
  if [ $? = 0 ]
  then
  limite=$(echo "$user" |awk -F : '{print $3}')
  useradd -M -s /bin/false $usuario
  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
  limit $usuario $limite 1> /dev/null 2> /dev/null
  echo "$senha" > /etc/gerenciadorinfo/senha/$usuario
  else
  useradd -M -s /bin/false $usuario
  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
  echo "$senha" > /etc/gerenciadorinfo/senha/$usuario
  fi
  echo -e "\033[1;37mUsuario: \033[1;36m$usuario \033[1;37mBackup: [\033[1;36mOk\033[1;37m]\033[0m"
fi
done
}
function banner(){
sshd_config_bak=$(cat /etc/ssh/sshd_config |grep -v "Banner")
echo "$sshd_config_bak" > /etc/ssh/sshd_config
echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
service ssh restart 1>/dev/null 2>/dev/null
service sshd restart 1>/dev/null 2>/dev/null
if [ -f /etc/bannerssh ]
then
banner=$(cat /etc/bannerssh)
else
banner="No hay un banner de momento"
fi
echo -e "\033[1;32mBanner atual\n\n\033[1;37m$banner\n\033[0m"
echo "Cual es el banner que desea agregar (ctrl + c para salir )"
read -p ": " bannerssh
echo "$bannerssh" > /etc/bannerssh
service ssh restart 1> /dev/null 2>/dev/null
service sshd restart 1>/dev/null 2>/dev/null
}
function deletar_todos(){
for user in $(cat /etc/passwd |awk -F : '$3 > 900 {print $1}' |grep -v "rick" |grep -vi "nobody")
do
userpid=$(ps -u $user |awk {'print $1'})
kill "$userpid" 2>/dev/null
userdel $user
echo "$user Eliminado"
done
}
function tools(){
toolmaster
}
clear
if [[ $1 == "" ]]
then
echo -e "\033[1;37m==================================================================\033[0m"
echo -e "\033[1;37m           ∆  VPS Manager - V3.0  The DarkSide\033[0m"
echo -e "\033[1;37m==================================================================\033[0m"
echo -e "\033[1;37m==================================================================\033[0m"
echo -e "\033[1;33m       ∆  ¡Bienvenido al Menú!:    Para Salir pulse Ctrl + C\033[1;33m
[\033[1;36m01 •\033[1;33m] Configurar_Squid_SSH_Dropbear \033[1;37m(Configuracion Squid, OpenSSH y Dropbear)\033[1;33m
[\033[1;36m02 •\033[1;33m] Limite \033[1;37m(Limite de Conexiones simultaneas)\033[1;33m
[\033[1;36m03 •\033[1;33m] Crear_Usuario \033[1;36m(Crear usuarios)\033[1;33m
[\033[1;36m04 •\033[1;33m] Remover_Expirados \033[1;37m(Remover Usuarios expirados)\033[1;33m
[\033[1;36m05 •\033[1;33m] Crear_Prueba \033[1;37m(Crear usuarios de corta duracion)\033[1;33m
[\033[1;36m06 •\033[1;33m] BadVpn \033[1;37m(Instala BadVpn para tunnel udp)\033[1;33m
[\033[1;36m07 •\033[1;33m] BadVpn_Iniciar \033[1;37m(Activar llamadas VoIP, Juegos Online, etc)\033[1;33m
[\033[1;36m08 •\033[1;33m] BadVpn_Stop \033[1;37m(Parar servicio de BadVpn)\033[1;33m
[\033[1;36m09 •\033[1;33m] Remover_Limite \033[1;37m(Remover limite de conexiones de un usuario)\033[1;33m
[\033[1;36m10 •\033[1;33m] Cambiar_Nombre \033[1;37m(Cambiar nombre de un usuario)\033[1;33m
[\033[1;36m11 •\033[1;33m] Reconfigurar_Usuario \033[1;37m(Cambiar Fecha, Contraseña, etc)\033[1;33m
[\033[1;36m12 •\033[1;33m] Eliminar_Usuario \033[1;37m(Menu Eliminar, Desconectar, etc)\033[1;33m
[\033[1;36m13 •\033[1;33m] Firewall_Block \033[1;37m(Bloquear torrent, icmp [\033[1;36mRIESGO\033[1;30m])\033[1;33m
[\033[1;36m14 •\033[1;33m] Reset_Firewall \033[1;37m(Resetear reglas iptables [\033[1;36mRIESGO\033[1;30m])\033[1;33m
[\033[1;36m15 •\033[1;33m] Addhost \033[1;37m(Agregar Hosts )\033[1;33m
[\033[1;36m16 •\033[1;33m] Remover_Host \033[1;37m(Remover Hosts)\033[1;33m
[\033[1;36m17 •\033[1;33m] Monitorear \033[1;37m(Monitorear Conexiones)\033[0m\033[1;33m
[\033[1;36m18 •\033[1;33m] Respaldo_Users \033[1;37m(Respaldo de usuarios)\033[1;33m
[\033[1;36m19 •\033[1;33m] Reset_Users \033[1;37m(Restaurar usuarios de un Respaldo)\033[1;33m
[\033[1;36m20 •\033[1;33m] Usuarios_Detalles \033[1;37m(Informacion sobre los usuarios !!)\033[1;33m
[\033[1;36m21 •\033[1;33m] Agregar Banner \033[1;37m(Agregar un banner, introduce tu Codigo HTML)\033[1;33m
[\033[1;36m22 •\033[1;33m] Speedtest \033[1;37m(Prueba de conexion [velocidad de banda])\033[1;33m
[\033[1;36m23 •\033[1;33m] Sistema_Detalles \033[1;37m(Detalles sobre el Sistema)\033[1;33m
[\033[1;36m24 •\033[1;33m] Eliminar_Todos \033[1;37m(Todos los usuarios seran eliminados)\033[1;33m
[\033[1;36m25 •\033[1;33m] Desinstalar \033[1;37m(Remover Vps Manager)\033[1;33m
[\033[1;36m26 •\033[1;33m] Dropbear \033[1;37m(Ver usuarios conectados en Dropbear)\033[1;33m
[\033[1;36m27 •\033[1;33m] Shadowshocks_Install \033[1;37m(Instalar Shadowsocks)\033[1;33m
[\033[1;36m28 •\033[1;33m] Shadowshocks_Start \033[1;37m(Activar Shadowsocks)\033[1;33m
[\033[1;36m29 •\033[1;33m] Shadowshocks_stop \033[1;37m(Parar Shadowsocks)\033[1;33m
[\033[1;36m30 •\033[1;33m] Ver_Puertos \033[1;37m(Ver puertos abiertos)\033[1;33m
[\033[1;36m31 •\033[1;33m] Banner_Plantilla \033[1;37m(Banner Preconfigurado)\033[1;33m
[\033[1;36m32 •\033[1;33m] Stunnel \033[1;37m(Instalar Certificado SSL)\033[1;33m
[\033[1;36m33 •\033[1;33m] Install_Keygen \033[1;37m(Vende Keys ADM-OLD)\033[1;33m"
echo -e "\033[1;37m==================================================================\033[0m"
read -p "[Seleccione Opción]: " opcao
else
opcao=$1
fi
case $opcao in
  1 | 01 )
   configurarsquid;;
  2 | 02 )
   read -p "Usuario: " user
   read -p "Limite: " limite
   limite $user $limite;;
  3 | 03 )
   criarusuario;;
  4 | 04 )
   removerexpirados;;
  5 | 05 )
   criarusuarioteste;;
  6 | 06 )
   badvpn_install;;
  7 | 07 )
   badvpn start;;
  8 | 08 )
   badvpn stop;;
  9 | 09 )
   removerlimite;;
  10)
   mudarnome;; 
  11)
   redefinirusuario;;
  12)
   deletarusuario;;
  13)
   firewallblock;;
  14)
   resetfirewall;;
  15)
   addhost;;
  16)
   removerhost;;
  17)
   monitorar;;
  18)
   backup_de_usuarios;;
  19)
   restaurar_usuarios;;
  20)
   detalhes_usuarios;;
  21)
   banner.sh;;
  22)
   speedtest.py;;
  23)
   sistemadetalhes;;
  24)
   deletar_todos;;
  25)
   rm -rf /bin/speedtest.py 2>/dev/null
   rm -rf /bin/deletarusuario 2>/dev/null
   rm -rf /bin/redefinirusuario 2>/dev/null
   rm -rf /bin/limite 2>/dev/null
   rm -rf /bin/criarusuario 2>/dev/null
   rm -rf /bin/vpspack 2>/dev/null;;
   26)
   dropbear;;
   27)
   shadowsocks_install;;
   28)
   ssserver -c /etc/shadowsocks.json -d start;;
   29)
   ssserver -c /etc/shadowsocks.json -d stop;;
   30)
   netstat -tunlp;;
   31)
   new_banner;;
   32)
   stunnel;;
   33)
   install_keygen;;
  esac
